# Generated by Django 4.0.5 on 2022-06-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(verbose_name='id user')),
                ('name', models.TextField(verbose_name='user name')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
